/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "RCC_interface.h"
#include "RCC_private.h"
#include "GPIO_Interface.h"
#include "keypad.h"
#include "usart_interface.h"


int main(){
//

		//RCC/
		RCC_voidInit();
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOA_EN);
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOB_EN);
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOC_EN);


				//Keypad
				KeyPad_Intialize();
				u8 key;
				//usart2 enable
				delay(500);
				USART_voidInit();// initialize UART
				//delay(500);
		L:
				for (int i = 0 ; i < 6 ; i++)
				{
				key = KeyPad_getPressedKey();
					if (key >0 && key <= 9)
					{ delay(150);
					  USART_voidTransmit(key);
					  delay(500);
					}//end if
				}//end for
				for(;;)
				{
					if (USART_u8Receive() == 1 )
					{
						delay(100);
						goto	L;
					}
				}
				}//end main























