/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
  *****************************************************************************/
#include "main.h"

/*****************EXTERNAL INTERRUPT FUNCTION FOR CARS MOVING IN****************************/

/*
 * Gets Car Count for cars leaving the parking and opens then closes the door
 */
void Application1(void)// car moving out
{

	LCD_voidWriteCmd(0x01);// Clear LCD

	if (car_count == no_car_count)// if parking is empty
		{
		LCD_void_goto(1, 3);
		DCmotor_Stop();
		LCD_void_write_string((u8*)"PARKING EMPTY");
		}
	else if (car_count >= no_car_count)
		{

		car_count --;
		LCD_void_write_string((u8*)"Car Leaving");
		LCD_void_goto(1, 3);
		LCD_void_write_string((u8*)"Total Cars:");
		LCD_void_print_unsigned_integer(car_count);
		SEVSEG_VoidDisplay(SEG0, car_count);
		EXTI_voidDisableLine(EXTI_LINE5);
		Open_Door();
		EXTI_voidEnableLine(EXTI_LINE5);
		Close_Door();
		LCD_voidWriteCmd(0x01);// Clear LCD
		LCD_void_goto(1, 3);
		LCD_void_write_string("Total Cars:");
		LCD_void_print_unsigned_integer(car_count);
		SEVSEG_VoidDisplay(SEG0, car_count);
		Close_Door();
		LCD_voidWriteCmd(0x01);// Clear LCD
		LCD_void_goto(1, 3);
		LCD_void_write_string("Total Cars:");
		LCD_void_print_unsigned_integer(car_count);
		SEVSEG_VoidDisplay(SEG0, car_count);
		delay(500);
		DCmotor_Stop();
		Exit_Flag = 1;
		}


}
/************************************************************************************/
/*****************EXTERNAL INTERRUPT FUNCTION FOR CARS MOVING OUT****************************/

/*
 * Gets Car Count for cars going inside the parking and closes then opens the door
 */

void Application2(void)// car moving in
{

	LCD_voidWriteCmd(0x01);// clear lcd

		if (car_count == max_car_count)
		{
			LCD_void_goto(1, 3);
			DCmotor_Stop();
			LCD_void_write_string("PARKING FULL");
		}
		else if (car_count <= max_car_count)
		{
		car_count ++;
		LCD_void_write_string((u8*)"CAR IN");
		LCD_void_goto(1, 3);
		LCD_void_write_string("Total Cars:");
		LCD_void_print_unsigned_integer(car_count);
		SEVSEG_VoidDisplay(SEG0, car_count);
		EXTI_voidDisableLine(EXTI_LINE5);
		Open_Door();
		EXTI_voidEnableLine(EXTI_LINE5);
		Close_Door();
		LCD_voidWriteCmd(0x01);// Clear LCD
		LCD_void_goto(1, 3);
		LCD_void_write_string("Total Cars:");
		LCD_void_print_unsigned_integer(car_count);
		SEVSEG_VoidDisplay(SEG0, car_count);
		Close_Door();
		LCD_voidWriteCmd(0x01);// Clear LCD
		LCD_void_goto(1, 3);
		LCD_void_write_string("Total Cars:");
		LCD_void_print_unsigned_integer(car_count);
		delay(500);
		DCmotor_Stop();
		Exit_Flag =1;
		}

}

/************************************************************************************/
/*****************************************EXTI3*****************************************/
/*
 * This interrupt is of higher priority to be set once the flame sensor sends a HIGH signal
 */
void Application3(void)// car moving in
{
	LCD_voidWriteCmd(0x01);// clear lcd
	LCD_void_goto(0, 0);
	LCD_void_write_string("FIRE ALARM");
	LCD_void_goto(1, 0);
	LCD_void_write_string("PLEASE EXIT");
	Alarm_voidAlarmOn();
	Open_Door();
	LCD_void_goto(0, 0);
	LCD_void_write_string("FIRE ALARM");
	LCD_void_goto(1, 0);
	LCD_void_write_string("PLEASE EXIT");
	delay(500);

}
/************************************************************************************/
/*****************************************EXTI4*****************************************/
void Application4(void)//IR_u8GetState(IR1) == OBSTACLE
{


			LCD_voidWriteCmd(0x01);// clear lcd
			LCD_void_goto(0, 0);
			LCD_void_write_string("Please Wait");
			LCD_void_goto(1, 0);
			LCD_void_write_string("OBSTCALE FOUND");
			DCmotor_Stop();
			delay(500);


}

/************************************************************************************/
/*****************************************Main*****************************************/
int main(){

/*********************************************************************/
/*************************Local Variables*****************************/

	u8 data;
	u8 password[6];
	u8 Welcome_Flag = 0;
	u8 i;

/*********************************************************************/
/*********************************************************************/
	//RCC Enable for GPIO
		RCC_voidInit();
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOA_EN);
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOB_EN);
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOC_EN);
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOD_EN);
		RCC_voidEnablePeripheralCLK(RCC_AHB1,RCC_GPIOE_EN);

/*********************************************************************/
/*********************************************************************/
		// Intializations


		//Seven Segment Initialize
		SEVSEG_VoidInitialize(SEG0);
		SEVSEG_VoidEnable(SEG0);

		// LCD Initialization
		LCD_void_init(LCD_enum_4BITS_MODE);// 4 bits mode
		LCD_void_goto(0, 0);

		// DC Motor Initialization
		DCmotor_init();

		//Switch Initialization
		SW_voidIntialize(SW0);

		//flame sensor Initialization
		Flame_sensor_voidIntialize();

		//IR Initialization
		IR_voidIntialize(IR1);

		//Alarm Initialization
		Alarm_voidInit();

/*********************************************************************/
/*********************************************************************/


L:		LCD_voidWriteCmd(0x01);
		LCD_void_goto(0, 0);
		LCD_void_write_string("Insert Password:");
		LCD_void_goto(1, 0);


/*********************************************************************/
/*********************************************************************/

		//USART Initialize
		delay(500);
		USART_voidInit();// initialize UART


/*********************************************************************/
/*********************************************************************/

		// Start from the middle of the display
		LCD_void_goto(1, 5);

		//Recieve only 6 digits for password via USART
		for (i = 0 ; i < 6 ; i++)
	{
		data = USART_u8Receive();

		if (data >0 && data <= 9)// check that we received numbers from 1 to 9
		{
				password[i]=data;
				SEVSEG_VoidDisplay(SEG0, password[i]);
				LCD_void_print_unsigned_integer(data);
				LCD_void_goto(1, 5+i);
				delay(100);
				LCD_void_write_string("*");
				delay(500);

		}//end if
	}//end for

/*********************************************************************/
/*********************************************************************/


		//check that the password is 123456
		if ( Check_Password(password) == Correct_Password)
		{
			LCD_voidWriteCmd(0x01);
			LCD_void_goto(0, 0);
			LCD_void_write_string("Welcome");
			delay(300);
			LCD_voidWriteCmd(0x01);
			LCD_void_write_string("Total Cars:");
			LCD_void_print_unsigned_integer(car_count);
			delay(200);
			Welcome_Flag = 1;
			if (Welcome_Flag == 1)
			{
				EXTI_voidSetCallBack(Application1,Application2,Application3,Application4);

				Set_All_EXTI();//sets all external interrupts
			}//end if

			while(1)
			{
				if(SW_u8GetState(SW0) == PRESSED)
				{
					Alarm_voidAlarmOff();
					DCmotor_Stop();
					LCD_voidWriteCmd(0x01);
					LCD_void_goto(0, 0);
					LCD_void_write_string("Welcome");
					delay(200);

				}//end if

				if (Exit_Flag == 1)
				{

					USART_voidTransmit(1);
					Exit_Flag = 0;
					goto L;
				}
			}//end while(1)
		}//end if
/*********************************************************************/
/*********************************************************************/
		else	//if password is wrong
		{
			LCD_voidWriteCmd(0x01);
			LCD_void_goto(0, 3);
			LCD_void_write_string("Wrong Password");
			USART_voidTransmit(1);// transmit 1 as wrong password for the TX to transmit again
			delay(50);

			goto L;// go back to insert password
		}


		}//end main










































